"""add_ml_fields_and_model_path_rename

Revision ID: 2325fb33d1f5
Revises: d34ab4fecbf1
Create Date: 2026-06-26 12:03:57.366087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2325fb33d1f5'
down_revision: Union[str, Sequence[str], None] = 'd34ab4fecbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heatwave_predictions', sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('heatwave_predictions', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('imd_weather_data', sa.Column('mean_temp', sa.Float(), nullable=True))
    op.add_column('imd_weather_data', sa.Column('pressure', sa.Float(), nullable=True))
    op.add_column('imd_weather_data', sa.Column('solar_radiation', sa.Float(), nullable=True))
    op.add_column('model_registry', sa.Column('model_path', sa.String(length=512), nullable=False))
    op.drop_column('model_registry', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('file_path', sa.VARCHAR(length=512), nullable=False))
    op.drop_column('model_registry', 'model_path')
    op.drop_column('imd_weather_data', 'solar_radiation')
    op.drop_column('imd_weather_data', 'pressure')
    op.drop_column('imd_weather_data', 'mean_temp')
    op.drop_column('heatwave_predictions', 'confidence')
    op.drop_column('heatwave_predictions', 'shap_values')
    # ### end Alembic commands ###
