"""Initial schema

Revision ID: d34ab4fecbf1
Revises: 
Create Date: 2026-06-23 23:50:39.779862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34ab4fecbf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('PUBLIC', 'FARMER', 'TRAVELLER', name='advisoryrole'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'EXTREME', name='risklevel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('document_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_districts_name_state', 'districts', ['name', 'state'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PUBLIC', 'FARMER', 'TRAVELLER', 'RESEARCH', 'AUTHORITY', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('aerosol_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('aod_value', sa.Float(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'date', name='uq_aerosol_district_date')
    )
    op.create_index(op.f('ix_aerosol_data_date'), 'aerosol_data', ['date'], unique=False)
    op.create_index(op.f('ix_aerosol_data_district_id'), 'aerosol_data', ['district_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('issued_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'EXTREME', name='risklevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_district_id'), 'alerts', ['district_id'], unique=False)
    op.create_index(op.f('ix_alerts_issued_by_user_id'), 'alerts', ['issued_by_user_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uploaded_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('dataset_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='datasetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_uploaded_by_user_id'), 'datasets', ['uploaded_by_user_id'], unique=False)
    op.create_table('heatwave_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'EXTREME', name='risklevel'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heatwave_predictions_district_id'), 'heatwave_predictions', ['district_id'], unique=False)
    op.create_index(op.f('ix_heatwave_predictions_forecast_date'), 'heatwave_predictions', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_heatwave_predictions_prediction_date'), 'heatwave_predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_heatwave_predictions_risk_level'), 'heatwave_predictions', ['risk_level'], unique=False)
    op.create_table('imd_weather_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'date', name='uq_imd_weather_district_date')
    )
    op.create_index(op.f('ix_imd_weather_data_date'), 'imd_weather_data', ['date'], unique=False)
    op.create_index(op.f('ix_imd_weather_data_district_id'), 'imd_weather_data', ['district_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_imd_weather_data_district_id'), table_name='imd_weather_data')
    op.drop_index(op.f('ix_imd_weather_data_date'), table_name='imd_weather_data')
    op.drop_table('imd_weather_data')
    op.drop_index(op.f('ix_heatwave_predictions_risk_level'), table_name='heatwave_predictions')
    op.drop_index(op.f('ix_heatwave_predictions_prediction_date'), table_name='heatwave_predictions')
    op.drop_index(op.f('ix_heatwave_predictions_forecast_date'), table_name='heatwave_predictions')
    op.drop_index(op.f('ix_heatwave_predictions_district_id'), table_name='heatwave_predictions')
    op.drop_table('heatwave_predictions')
    op.drop_index(op.f('ix_datasets_uploaded_by_user_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_issued_by_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_district_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_aerosol_data_district_id'), table_name='aerosol_data')
    op.drop_index(op.f('ix_aerosol_data_date'), table_name='aerosol_data')
    op.drop_table('aerosol_data')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('model_registry')
    op.drop_index('idx_districts_name_state', table_name='districts')
    op.drop_table('districts')
    op.drop_table('advisories')
    # ### end Alembic commands ###
