"""add_district_id_to_user

Revision ID: fbefe293950b
Revises: a51c09938ef1
Create Date: 2026-08-10 22:13:02.504398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbefe293950b'
down_revision: Union[str, Sequence[str], None] = 'a51c09938ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('district_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'district_id')
    # ### end Alembic commands ###
